version: '3'
services:
  catalog.api:
    image: catalogapi
    container_name: catalogapi
    build: 
      context: ./Catalog.Api
      dockerfile: dockerfile

  catalog.db:
    image: mongo
    container_name: catalogdb

  basket.api:
    image: basketapi
    container_name: basketapi
    build: 
      context: ./Basket.Api
      dockerfile: dockerfile
  
  basket.db:
    image: redis
    container_name: redisdb

  
  discount.api:
    image: discountapi
    container_name: discountapi
    build: 
      context: ./Discount.Api
      dockerfile: dockerfile

  discount.db:
    image: postgres
    container_name: postgresdb
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    

