version: '3'
services:
  catalog.api:
    ports:
      - 4000:4300
    depends_on:
      - catalog.db
    environment:
      - MONGO_URL=catalogdb:27017
  catalog.db:
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongodb:/data/db
      - ./mongodb_configfolder:/data/configdb

  basket.api:
    ports:
      - 4100:5000
    depends_on:
      - basket.db
    volumes:
      - ./Basket.Api/appsettings.json:/app/appsettings.json
    restart: always
      
  basket.db:
    ports:
      - 6379:6379
    restart: always




  

