version: '3'
services:
  catalog.api:
    ports:
      - 4000:4300
    depends_on:
      - catalog.db
    environment:
      - MONGO_URL=catalogdb:27017
  catalog.db:
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongodb:/data/db
      - ./mongodb_configfolder:/data/configdb

  basket.api:
    environment:
      - "DiscountGrpcServerUrl=http://discountapi:5003"
    ports:
      - 4100:5000
    depends_on:
      - basket.db
    volumes:
      - ./Basket.Api/appsettings.json:/app/appsettings.json
    restart: always
      
  basket.db:
    ports:
      - 6379:6379
    restart: always

  discount.api:
    environment:
     - "DatabaseSettings:ConnectionString=Server=postgresdb;Port=5432;Database=DiscountDb;User Id=postgres;Password=123456;"
     - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
    ports:
      - 4200:5001
      - 4300:5003
    depends_on:
      - discount.db
    volumes:
      - ./Discount.Api/appsettings.json:/app/appsettings.json
    restart: always

  discount.db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=DiscountDb
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  
  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=mortezadalil@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234567
    ports:
      - 5050:80
    restart: always
    volumes:
      - pgadmin_data:/root/.pgadmin


volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:


  

